use_frameworks!

platform :ios, '11.0'

target 'NavigationBarExtension_Example' do
  pod 'NavigationBarExtension', :path => '../'

  target 'NavigationBarExtension_Tests' do
    inherit! :search_paths

    
  end
end
