import_from_git(url: 'ssh://git@codereview.technologies.fabernovel.com:29418/ADFastlane',
                path: 'Fastfile_ios.rb',
                branch: 'v7.1.0')


#####################################################
# @!group Configuration
#####################################################

override_lane :get_project_configuration do
  {
    xcworkspace: 'NavigationBarExtension.xcworkspace',
    xcodeproj: 'NavigationBarExtension.xcodeproj'
  }
end

override_lane :get_variants_build_configurations do
  {
    'NavigationBarExtension' => {
      scheme: 'NavigationBarExtension-Example',
      xcode_configuration: 'Release'
    }
  }
end

#####################################################
# @!group Codesign
#####################################################

override_lane :get_variants_codesign_configurations do
  MATCH_CUSTOMER_CONFIGURATION =
    {
      apple_id: nil,
      apple_id_password: lane_context[:ALL_CLI_OPTIONS][:apple_password],
      team_id: nil, # Available on developer.apple.com
      team_name: nil, # Available on developer.apple.com
      git_repository: "ssh://ci@codereview.technologies.fabernovel.com:29418/ADSigningAssetsCustomers",
      git_branch: nil, # To create on the git repository. Guidelines: <client_name>_<team_id>
      git_password: lane_context[:ALL_CLI_OPTIONS][:match_password]
    }
  {
    'NavigationBarExtension' => {
      bundles: ["com.yourclient.appname"],
      fabernovel_bundles: ["com.applidium.NavigationBarExtension-Example"],
      provisioning_profile_templates: nil,
      match_configuration: MATCH_CUSTOMER_CONFIGURATION
    }
  }
end

override_lane :get_variants_itunes_connect_configurations do
  ITC_CUSTOMER_CONFIGURATION = {
    apple_id: "TODO",
    team_id: "TODO", # Run $ fastlane deliver init , to easily find it (will be between parenthesis)
    team_name: "TODO", # Also returned bu the command for team_id
    apple_id_password: lane_context[:ALL_CLI_OPTIONS][:apple_password],
    itc_provider: "TODO" # Use /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter -u YOUR_APPLE_ID -p YOUR_PASSWORD -account_type itunes_connect -v off -m provider
  }
  {
    'NavigationBarExtension' => ITC_CUSTOMER_CONFIGURATION
  }
end

#####################################################
# @!group CI
#####################################################

override_lane :get_variants_to_build_on_ci do |options|
  case options[:commit_type]
  when 'merge'
    variants = ['NavigationBarExtension']
  when 'release'
    variants = ['NavigationBarExtension']
  else
    variants = ['NavigationBarExtension']
  end
  variants
end

#####################################################
# @!group Tests
#####################################################

override_lane :get_project_tests_configurations do
  {
    'NavigationBarExtension_Tests' => {
      display_name: 'NavigationBarExtension UI Tests',
      scheme: 'NavigationBarExtension-Example',
      app_bundle: 'com.applidium.NavigationBarExtension-Example',
      xcode_configuration: 'Debug',
      unit_tests_bundles: ['NavigationBarExtension_Tests'],
      ui_tests_bundles: nil,
      devices: ['iPhone SE'],
      languages: ['fr-FR'],
      os_versions: nil, # Use nil to use the latest, otherwise ['11.3', '11.2']
      reinstall_app: true,
      screenshots_output_path: './screenshots',
      sonar_properties_file: nil,
      disable_concurrent_testing: false
    }
  }
end

override_lane :get_test_configurations_for_ci do |options|
  case options[:commit_type]
  when 'merge'
    test_configurations = ['NavigationBarExtension_Tests']
  when 'release'
    test_configurations = ['NavigationBarExtension_Tests']
  else
    test_configurations = ['NavigationBarExtension_Tests']
  end
  test_configurations
end